apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: python-spark
  namespace: default
spec:
  type: Python
  pythonversion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v2.4.5"
  imagePullPolicy: Always
  mainApplicationFile: "hdfs://hadoop-hadoop-hdfs-nn:9000/app/pyspark_driver.py"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.5